#!/bin/sh
# SysV-style initscript (fedora, etc.)
# dataqd: Pop filename with checksum from queue and apply an action to it.
#
# chkconfig:   - 40 60
# description: Pops filename and checksum from queue and applies an action \
#              to the file.

#! ### BEGIN INIT INFO
#! # Provides: 
#! # Required-Start: 
#! # Required-Stop: 
#! # Should-Start: 
#! # Should-Stop: 
#! # Default-Start: 
#! # Default-Stop: 
#! # Short-Description: 
#! # Description:      
#! ### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/dqsvcpop"  # /path/to/<daemonname>
prog="dataq"              # <service name>
#!config=""               # <path to major config  file>
piddataq="/var/run/dataq"
poplog=/var/log/tada/pop.log

# Load env vars representing config
[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    # if not running, start it up here, usually something like "daemon $exec"
    daemon --pidfile=${piddataq} $exec < /dev/null > $poplog 2>&1 &
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    # stop it here, often "killproc $prog"
    #!killproc $prog
    pkill `basename $exec`  # 
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
